spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                -  Path=/api/v1/products/**
            - id: payment-service
              uri: http://localhost:8082
              predicates:
                -  Path=/api/v1/payments/**
            - id: card-service
              uri: lb://card-service
              predicates:
                - Path=/api/v1/cards/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888
